### PR TITLE
fix failing tests in t/02_prepare_serializer_for_format.t: the serialize...

### PR DESCRIPTION
**Pull request by emil-perhinschi**
the serializer is surviving across requests if not set explicitly, so if a YAML request was processed, the next "/" request (which does not come with a serializer) would have the content type text/x-yaml and be encoded with YAML instead of 'text/html' and no serialization

probably should be fixed in Dancer2 but I did not find yet where to do it

### CODE REVIEW

**Comment by shlomif** [comment]
I tested this pull-request and it indeed fixes the tests. Good job! I was planning to do one myself.

@yanick : why didn't you pull this yet, and made a new release? Because of this, I had had to use Dancer 1 instead of Dancer2 for a project I wrote.

**Comment by bigpresh** [comment]
This sounds more like a Dancer2 bug that needs fixing rather than implementing a hacky workaround, if I'm reading it right.  Has a bug been raised against D2 for this behaviour?  Is it still an issue with the latest D2 release without this patch?

**Comment by shlomif** [comment]
@bigpresh: I'm not aware of a bug filed against Dancer2 for it. And the tests for perl-Dancer2-Plugin-REST still fail here on Mageia Linux x86-64 6/Cauldron with perl-5.22.0-6.mga6 and the latest version of Dancer2 (0.162000). I'll try to see if I can provide a patch against the upstream Dancer2.

**Comment by emil-perhinschi** [comment]
there is a bug report on Dancer2: https://github.com/PerlDancer/Dancer2/issues/901

**Comment by shlomif** [comment]
@emil-perhinschi  : thanks for the link.

**Comment by bigpresh** [comment]
Having looked at this in more detail, it seems that the serialiser setting surviving across requests is because `Dancer2::Plugin::REST` sets it using the `set` keyword, as well as passing it to the response:

```perl
            $dsl->set(serializer => $serializer);
            $dsl->app->set_response( Dancer2::Core::Response->new(
                %{ $dsl->app->response },
                serializer => $dsl->set('serializer'),
            ) );
```

It looks like that first line there is the issue; with it set using `set` (amending an app-wide setting), I'd expect that to survive between requests.  Let's see if the issue still happens if that line is removed, and if the `serializer` passed to the new `Dancer2::Core::Response` object is enough to override the serialiser solely for that request...

**Comment by emil-perhinschi** [comment]
this is not necessarily a bug, it kind of makes sense to keep the serializer 

just needs a proper documented method to unset it instead of deleting directly in the hash

**Comment by bigpresh** [comment]
I think a serialiser set by `set` staying set until unset is entirely reasonable and not a bug, correct.

It should be possible to set it for a single request by passing it to `Dancer2::Core::Response` on creation, exactly as D2::P::REST is doing - but it looks like it needs to be turned into a proper serialiser object first, which happens automatically in the code above because calling `$dsl->set` will have done it.  Looking in to a clean way for that code to take the serialiser name and turn it into a serialiser object which it can pass to the response object now - I need to refresh myself on how D2 engines work.  I can get a serializer engine object with e.g. `$dsl->engine('serializer')` - but that only works if I've set it globally with `set` and let it be compiled to a configured serializer engine object, which then leaves it set for other requests.

The approaches I think could work:

* D2::Plugin::REST could just store the original serializer setting before modifying it, passing the engine object to the response object, then set it back to what it was before
* D2::Core::Response could be tweaked so that if it's given a `serializer` attribute and it's a straight scalar, it does whatever is needed in the background to turn that into a serializer object it can use to serialize that response when needed, without it having had to be actually set as the app's serializer, so it won't affect any other responses except the response object instance we provided it to (my preference)
* D2 could expose an easy method to fetch a new engine of any type without it being set by set - for instance, being able to say `my $serializer = $dsl->engine( serializer => 'JSON' )` and get back a serializer object configured and ready to use.

The latter two approaches both require an ability to get an engine object of a specified type configured and ready to use without having had to actually set them in the app, so may require parts of `_compile_config_entry` from `Dancer2::Core::Role::ConfigReader` to be refactored out.

Comments on the above ideas welcome!

**Comment by yanick** [comment]
For the  record, I'm waiting for the verdict on the Dancer2::Plugin2 changes (PerlDancer/Dancer2#1010) to do any work on Dancer2 plugins.

**Pull request closed without merging**
